ALTER TABLE bookings ADD COLUMN type VARCHAR(100);
ALTER TABLE bookings ADD COLUMN status VARCHAR(100);
ALTER TABLE bookings ADD COLUMN expiration TIMESTAMP;
ALTER TABLE bookings ADD COLUMN price REAL;

